-- Parte I

-- Consulta 1

-- id_factura, fecha_factura, vr_antes_iva por vendedor pablo marmol, clientes ciudad medellin
-- Tablas: Factura, cliente y vendedor

SELECT F.id_factura, F.fecha_factura, F.vr_antes_iva
FROM FACTURAS F 
JOIN VENDEDORES V ON (V.ID_VENDEDOR = F.FK_VENDEDORES)
JOIN CLIENTES CLI ON (CLI.ID_CLIENTE = F.FK_CLIENTES)
WHERE V.VENDEDOR = UPPER('Pablo Marmol') AND CLI.CIUDAD_CL = UPPER('Medellin');

-- Consulta 2
-- Tablas: Cliente

SELECT
    'El Cliente ' ||  
    INITCAP(SUBSTR(NOMBRE_CL, INSTR(NOMBRE_CL, ' ') + 1)) || 
    ' ' || 
    INITCAP(SUBSTR(NOMBRE_CL, 1, INSTR(NOMBRE_CL, ' ') - 1)) ||
    CASE SEGMENTO_CL
        WHEN 'HOMBRE' THEN ' es un '
        ELSE ' es una ' 
    END || 
    INITCAP (SEGMENTO_CL) ||
    ' que reside en la ciudad ' ||
    INITCAP(CIUDAD_CL) ||
    ' del País ' ||
    INITCAP(PAIS_CL) AS "Informacion Clientes"
FROM CLIENTES
WHERE SEGMENTO_CL = 'HOMBRE' OR SEGMENTO_CL = 'MUJER';

-- Consulta 3
-- Tablas: Vendedores, Facturas, Canales

SELECT V.VENDEDOR, F.FECHA_FACTURA, F.TOTAL_FACTURA, CANALES.CANAL_VENTA
FROM FACTURAS F
JOIN VENDEDORES V ON (V.ID_VENDEDOR = F.FK_VENDEDORES)
JOIN CANALES ON (CANALES.ID_CANAL = F.FK_CANALES)
ORDER BY V.VENDEDOR ASC, CANALES.CANAL_VENTA DESC;

-- Consulta 4
-- Tablas: Sucursales, Clientes, Servicios, Cobranzas

SELECT SUC.SUCURSAL, SERV.ID_SERVICIO, SERV.COSTO_SERVICIO, CLI.NOMBRE_CL
FROM SERVICIOS SERV
JOIN SUCURSALES SUC ON (SERV.FK_SUCURSALES = SUC.ID_SUCURSAL)
JOIN CLIENTES CLI ON (SERV.FK_CLIENTES = CLI.ID_CLIENTE)
JOIN COBRANZAS 
WHERE 
    CLI.SEGMENTO_CL = 'HOMBRE'
    ;

SELECT 
    -- COUNT(*)
    CLI.NOMBRE_CL, 
    CLI.ID_CLIENTE, 
    F.FK_CLIENTES FAC_CLI,
    COB.FK_CLIENTES COB_CLI,
    F.ID_FACTURA,
    F.VR_ANTES_IVA,
    COB.FK_FACTURAS COB_FAC, 
    COB.ID_COBRANZA,
    COB.VALOR_COBRADO
FROM CLIENTES CLI
JOIN FACTURAS F ON (F.FK_CLIENTES = CLI.ID_CLIENTE)
JOIN COBRANZAS COB ON (COB.FK_FACTURAS = F.ID_FACTURA)
WHERE F.FK_CLIENTES = COB.FK_CLIENTES
ORDER BY CLI.NOMBRE_CL, F.ID_FACTURA;

SELECT 
    COUNT(*)
    -- CLI.ID_CLIENTE
FROM COBRANZAS COB
JOIN CLIENTES CLI ON (COB.FK_CLIENTES = CLI.ID_CLIENTE)
JOIN SERVICIOS SERV ON (CLI.ID_CLIENTE = SERV.FK_CLIENTES)
WHERE SERV.FK_CLIENTES = COB.FK_CLIENTES;

SELECT 
    SERV.ID_SERVICIO, CLI.ID_CLIENTE, F.ID_FACTURA
FROM SERVICIOS SERV
JOIN CLIENTES CLI ON (SERV.FK_CLIENTES = CLI.ID_CLIENTE)
JOIN FACTURAS F ON (F.FK_CLIENTES = CLI.ID_CLIENTE)
-- GROUP BY (SERV.ID_SERVICIO, CLI.ID_CLIENTE)
ORDER BY TO_NUMBER(CLI.ID_CLIENTE) ASC;

SELECT DISTINCT COUNT(*)
FROM CLIENTES CLI
JOIN SERVICIOS SERV ON (CLI.ID_CLIENTE = SERV.FK_CLIENTES);
-- GROUP BY (CLI.ID_CLIENTE);


SELECT COUNT(*)
FROM CLIENTES CLI
JOIN COBRANZAS COB ON (COB.FK_CLIENTES = CLI.ID_CLIENTE);

SELECT COUNT(*) FROM COBRANZAS COB;
SELECT * FROM SUCURSALES;
SELECT COUNT(*) FROM CLIENTES;

SELECT TO_DATE('06/01/2024') - TO_DATE('05/01/2024') DATES FROM DUAL;

-- Consulta 5
-- Tablas: Clientes, Facturas

SELECT F.ID_FACTURA, F.TOTAL_FACTURA, CASE (CLI.SEGMENTO_CL) 
    WHEN 'MUJER' THEN
        UPPER('segmento ' || CLI.SEGMENTO_CL || ' reside en el país ' || CLI.PAIS_CL)
    WHEN 'HOMBRE' THEN 
        UPPER('segmento ' || CLI.SEGMENTO_CL || ' reside en la ciudad ' || CLI.CIUDAD_CL)
    END Mensaje
FROM FACTURAS F
JOIN CLIENTES CLI ON (F.FK_CLIENTES = CLI.ID_CLIENTE)
WHERE 
    CLI.PAIS_CL = 'PER�' AND
    (CLI.SEGMENTO_CL = 'HOMBRE' OR CLI.SEGMENTO_CL = 'MUJER');
